# Generated by Django 4.1.4 on 2023-08-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_alarm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='song',
            new_name='songs',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='time',
        ),
        migrations.AddField(
            model_name='alarm',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
