# Generated by Django 4.1.4 on 2023-08-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_rename_song_alarm_songs_remove_alarm_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='songs',
            field=models.FileField(blank=True, null=True, upload_to='alarm'),
        ),
    ]
